language: r
cache:
  packages: true
  directories:
    - julia
    - $HOME/R/Library

env:
 - R_LIB_USER=$HOME/R/Library JULIA_BINDIR=$HOME/julia/julia-1.0.5/bin
 - R_LIB_USER=$HOME/R/Library JULIA_BINDIR=$HOME/julia/julia-1.3.0/bin

before_install:
  - mkdir julia && cd julia
  - wget https://julialang-s3.julialang.org/bin/linux/x64/1.0/julia-1.0.5-linux-x86_64.tar.gz
  - tar -xzf julia-1.0.5-linux-x86_64.tar.gz
  - wget https://julialang-s3.julialang.org/bin/linux/x64/1.3/julia-1.3.0-linux-x86_64.tar.gz
  - tar -xzf julia-1.3.0-linux-x86_64.tar.gz

r_packages:
  - covr

after_success:
  - test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'