language: r
cache:
  packages: true
  directories:
    - $HOME/julia

env:
 - JULIA_BINDIR=$HOME/julia/julia-1.0.5/bin
 - JULIA_BINDIR=$HOME/julia/julia-1.3.0/bin

before_install:
  - mkdir -p $HOME/julia
  - if ! [ -f $HOME/julia/julia-1.0.5 ]; then
      cd $HOME/julia;
      wget https://julialang-s3.julialang.org/bin/linux/x64/1.0/julia-1.0.5-linux-x86_64.tar.gz;
      tar -xzf julia-1.0.5-linux-x86_64.tar.gz;
      cd -;
    fi
  - if ! [ -f $HOME/julia/julia-1.3.0 ]; then
       cd $HOME/julia;
       wget https://julialang-s3.julialang.org/bin/linux/x64/1.3/julia-1.3.0-linux-x86_64.tar.gz;
       tar -xzf julia-1.3.0-linux-x86_64.tar.gz;
       cd -;
    fi

r:
  - oldrel
  - release
  - devel

r_packages:
  - covr

after_success:
  - if [[ $TRAVIS_R_VERSION_STRING == 'release' ]] && [[ $JULIA_BINDIR == *"1.0.5"* ]]; then
      Rscript -e 'covr::coveralls()';
    fi